### ISSUE TITLE
Implement Devise gem

### ISSUE THREAD

**Issue by ja-homebase** [devjona/blog-with-tags_rails#13]
Implement devise.

- Only the blog owner should be able to **create/edit/delete** articles and **add/edit/delete** tags.
- Only the blog owner should be able to delete comments.

Start with the basics first.

**Comment by devjona** [comment]
# Notes:
## After I installed:
```      create  config/initializers/devise.rb
      create  config/locales/devise.en.yml
===============================================================================

Depending on your application's configuration some manual setup may be required:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

     * Required for all applications. *

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

     * Not required for API-only Applications *

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

     * Not required for API-only Applications *

  4. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

     * Not required *

===============================================================================
```

FYI in case you need to refer to this.

**Comment by devjona** [comment]
# Next Steps:
1. I need a `login` page
2. I need to limit that only the `author` of a post can CRUD

Do I need `CanCanCan` to assign different roles to different users? I'd like people to be able to log in and comment but they can't edit the posts.

**Comment by devjona** [comment]
Test comment. Is this going to incorrect email?

**Comment by devjona** [comment]
# Progress:
- I can now log in as User, and show logged in status
- Can Log out
- Most article actions restricted to logged in user except for index, show
- Wrapped h1 header in an ugly link so user can always go to homepage
- Conditinally showing the 'edit/delete' links on an article page for logged in user only.

## Next Steps:
Write some tests with MiniTest!

Action list:
- [ ] Read about how to test this with MiniTest; what kind of test is it? Feature? Unit?
- [ ] Do it.
